set nocompatible
set modeline

filetype off

set rtp+=~/.vim/bundle/Vundle.vim " Install dir for vundle
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Directory Tree View
" usage enter :NERDTree in ex mode
Plugin 'scrooloose/nerdtree'

" Indent Seeing
Plugin 'nathanaelkane/vim-indent-guides'

" Xml
Plugin 'vim-scripts/xmledit'

" Velocity
Plugin 'lepture/vim-velocity'

Plugin 'vim-scripts/TortoiseSVN.vim'

" Alignment
Plugin 'junegunn/vim-easy-align'

" Read properties file
Plugin 'kamichidu/vim-edit-properties'

call vundle#end()
filetype plugin indent on

:let g:tortoiseSvnCmd='c:\Program Files\TortoiseSVN\bin\TortoiseProc.exe'
:let g:NERDTreeDirArrows=1
:let g:NERDTreeDirArrowExpandable='>'
:let g:NERDTreeDirArrowCollapsible='v'

" edit settings
"" tab width on screen
set tabstop=4
"" tab width auto indent
set shiftwidth=4
"" tab to space
set expandtab
"" Use tab on XML editing
augroup fileTypeIndent
    autocmd!
    autocmd BufNewFile,BufRead *.xml setlocal noet "noexpandtab
augroup END
"" Disable auto formatting on long line(tw)
set textwidth=0
"" Show line number(nu)
set number
"" Share OS clipboard
set clipboard=unnamed
"" Soft wrap when over editor area
set wrap
"" Disable auto insert comment characters
"set fo-=ro " but not working
"" show white space
set list
set listchars=tab:>_,trail:_

" Highlignt current cursor line(cul)
set cursorline
augroup cursorline
    au!
    au BufNewFile,BufRead * call s:set_cursorline()
    function! s:set_cursorline()
        hi clear CursorLine
        hi CursorLineNr ctermbg=DarkGreen
    endfunction
augroup END

" ZIPC special settings
augroup zipcType
    autocmd!
    autocmd BufNewFile,BufRead *.func,*.str,*.var,*.def,*.flow set ft=c 
    autocmd BufNewFile,BufRead *.func,*.str,*.var,*.def,*.flow set fencs=cp932
    autocmd BufNewFile,BufRead *.func,*.str,*.var,*.def,*.flow set fenc=cp932
augroup END

" indent guide options(:h indent_guides)
colorscheme default
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_start_level=1
let g:indent_guides_guide_size=2
let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']

" Alignment
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" Velocity
aug filetypeplugin
    au! BufRead,BufNewFile *.vm
    au BufRead,BufNewFile *.vm set ft=html syntax=velocity
aug end


" Mapping
inoremap jj <ESC>
"" Add blank line
nnoremap <silent><S-CR> o<ESC>
"" Toggle directory window
nnoremap <silent><C-t> :NERDTreeToggle<CR>
"" Move down(visual line)
nnoremap <silent>j gj
"" Move up(visual line)
nnoremap <silent>k gk
"" Open _vimrc
nmap <F2> :tabnew $MYVIMRC<CR>
"" grep next
map gn :cn<CR>
map gp :cp<CR>

" disable undo file
set undodir=
set undofile
" disable backup
"set nobackup

" ウインドウの幅
set columns=150
" ウインドウの高さ
set lines=45

" Auto reload .vimrc when save
augroup source-vimrc
  autocmd!
  autocmd BufWritePost *vimrc source $MYVIMRC | set foldmethod=marker
  "autocmd BufWritePost *gvimrc if has('gui_running') source $MYGVIMRC
augroup END
