set nocompatible

filetype off

set rtp+=~/.vim/bundle/Vundle.vim " vundleのインストール先
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Directory Tree View
" usage enter :NERDTree in ex mode
Plugin 'scrooloose/nerdtree'

" Indent Seeing
Plugin 'nathanaelkane/vim-indent-guides'

" Xml
Plugin 'vim-scripts/xmledit'

call vundle#end()
filetype plugin indent on

" edit settings
set tabstop=4
set shiftwidth=4
"自動折り返しを無効化
set textwidth=0
set expandtab
set number
set clipboard=unnamed,autoselect

" indent guide options
colorscheme default
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1

" Mapping
inoremap jj <ESC>
nnoremap <silent><CR> o<ESC>
nnoremap <silent><C-t> :NERDTreeToggle<CR>
nnoremap <silent>j gj
nnoremap <silent>k gk

" disable undo file
set undodir=

" ウインドウの幅
set columns=120
" ウインドウの高さ
set lines=40
